### ISSUE TITLE
"can't convert null to object" error when installed alongside EPiServer.Labs.LanguageManager 

### ISSUE THREAD

**Issue by JSkibinski** [episerver/EPiServer.Labs.ProjectEnhancements#1]
Hello

When creating new project an error is shown

![image](https://user-images.githubusercontent.com/70514008/116662419-0c363600-a996-11eb-9f10-df87b70561e2.png)

Caused by "TypeError: can't convert null to object" thrown in EPiServer.Labs.LanguageManager/4.0.1/ClientResources/LanguageManager/packaged.js

![image](https://user-images.githubusercontent.com/70514008/116662756-78b13500-a996-11eb-9fd1-23eb9b0fc404.png)

Error can be replicated by installing both packages in Alloy project, EPiServer.Labs.ProjectEnhancements 0.1.2 and EPiServer.Labs.LanguageManager 4.0.1, and creating new project

**Comment by barteksekula** [comment]
Hi, I'm not able to reproduce this issue.
Could you please try to reproduce in Alloy attached to this repository?
Just clone the repo and run from VS or use the steps from here https://github.com/episerver/EPiServer.Labs.ProjectEnhancements#development-in-this-repository
![project-enhancements](https://user-images.githubusercontent.com/1321664/117411403-cf2cef00-af13-11eb-850a-ad4ade50301a.gif)

**Comment by barteksekula** [comment]
Yes, I actually forgot that I reported the same issue you had to the Addons team and I can see they fixed it in 4.0.2.
I'm glad that it works for you now :)
